baseURL = "https://choosingwinetc.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "PaperMod"

[params]
  # PaperMod theme parameters
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true